CREATE TABLE IF NOT EXISTS subscription_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(128) NOT NULL,
    billing_type VARCHAR(32) NOT NULL DEFAULT 'fixed',
    monthly_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    yearly_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    seat_limit INT DEFAULT NULL,
    feature_flags JSON DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_code UNIQUE (plan_code)
);

CREATE TABLE IF NOT EXISTS tenant_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    subscription_status VARCHAR(32) NOT NULL DEFAULT 'trialing',
    started_at TIMESTAMP NOT NULL,
    expired_at TIMESTAMP DEFAULT NULL,
    seat_count INT NOT NULL DEFAULT 1,
    auto_renew_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tenant_status_expired
    ON tenant_subscription (tenant_id, subscription_status, expired_at);

CREATE TABLE IF NOT EXISTS usage_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    quota_code VARCHAR(64) NOT NULL,
    quota_limit INT NOT NULL DEFAULT 0,
    used_amount INT NOT NULL DEFAULT 0,
    reset_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_quota_code UNIQUE (tenant_id, quota_code)
);

