CREATE TABLE IF NOT EXISTS product_source_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    mapping_type VARCHAR(32) NOT NULL DEFAULT 'primary',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    risk_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mapping_store_product_supplier_type UNIQUE (store_id, product_id, supplier_id, mapping_type)
);

CREATE INDEX IF NOT EXISTS idx_mapping_store_product_active
    ON product_source_mapping (store_id, product_id, is_active);

CREATE INDEX IF NOT EXISTS idx_mapping_store_supplier_active
    ON product_source_mapping (store_id, supplier_id, is_active);

CREATE TABLE IF NOT EXISTS inventory_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    available_stock INT NOT NULL DEFAULT 0,
    reserved_stock INT NOT NULL DEFAULT 0,
    safety_stock INT NOT NULL DEFAULT 0,
    snapshot_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_store_product_sku_snapshot UNIQUE (store_id, product_id, sku_id, snapshot_at)
);

CREATE INDEX IF NOT EXISTS idx_inventory_store_safety
    ON inventory_snapshot (store_id, safety_stock, snapshot_at);

CREATE TABLE IF NOT EXISTS replenishment_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    suggested_qty INT NOT NULL DEFAULT 0,
    task_status VARCHAR(32) NOT NULL DEFAULT 'draft',
    approval_status VARCHAR(32) NOT NULL DEFAULT 'not_required',
    reason_text VARCHAR(512) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_replenishment_store_task_status
    ON replenishment_task (store_id, task_status, approval_status);

CREATE INDEX IF NOT EXISTS idx_replenishment_product_sku_status
    ON replenishment_task (product_id, sku_id, task_status);

