CREATE TABLE IF NOT EXISTS campaign_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    activity_type VARCHAR(32) NOT NULL,
    activity_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    start_at TIMESTAMP DEFAULT NULL,
    end_at TIMESTAMP DEFAULT NULL,
    product_ids_json TEXT DEFAULT NULL,
    rule_json TEXT DEFAULT NULL,
    coupon_template_id BIGINT DEFAULT NULL,
    need_approval BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_campaign_activity_store_status_time
    ON campaign_activity (store_id, status, start_at);

CREATE INDEX IF NOT EXISTS idx_campaign_activity_type_status
    ON campaign_activity (activity_type, status);

CREATE TABLE IF NOT EXISTS coupon_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    discount_type VARCHAR(32) NOT NULL,
    discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
    threshold_amount DECIMAL(10,2) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'enabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_coupon_template_store_status
    ON coupon_template (store_id, status);

