CREATE TABLE IF NOT EXISTS store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    owner_user_id VARCHAR(64) NOT NULL,
    platform_type VARCHAR(32) NOT NULL,
    platform_shop_id VARCHAR(64) NOT NULL,
    shop_name VARCHAR(128) NOT NULL,
    auth_status VARCHAR(32) NOT NULL DEFAULT 'disconnected',
    profit_threshold DECIMAL(10,2) NOT NULL DEFAULT 0,
    risk_threshold DECIMAL(10,2) NOT NULL DEFAULT 0,
    default_ship_config JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_platform_shop UNIQUE (tenant_id, platform_type, platform_shop_id)
);

CREATE INDEX IF NOT EXISTS idx_store_tenant_status
    ON store (tenant_id, auth_status);

CREATE TABLE IF NOT EXISTS channel_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    channel_type VARCHAR(32) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    auth_status VARCHAR(32) NOT NULL DEFAULT 'connected',
    expires_at TIMESTAMP DEFAULT NULL,
    extra_config JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_org_channel_status
    ON channel_account (organization_id, channel_type, auth_status);

